Пробуем API Mistral

In [ ]:
!pip install mistralai

Collecting mistralai
  Downloading mistralai-1.5.0-py3-none-any.whl.metadata (29 kB)
Collecting eval-type-backport>=0.2.0 (from mistralai)
  Downloading eval_type_backport-0.2.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.11/dist-packages (from mistralai) (0.28.1)
Collecting jsonpath-python>=1.0.6 (from mistralai)
  Downloading jsonpath_python-1.0.6-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.11/dist-packages (from mistralai) (2.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from mistralai) (2.8.2)
Collecting typing-inspect>=0.9.0 (from mistralai)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->mistralai) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->mistralai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->mistralai) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->mistralai) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.0->mistralai) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.0->mistralai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.0->mistralai) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9.0->mistralai) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->mistralai) (1.17.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.9.0->mistralai)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.0->mistralai) (1.3.1)
Downloading mistralai-1.5.0-py3-none-any.whl (271 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 271.6/271.6 kB 13.9 MB/s eta 0:00:00
Downloading eval_type_backport-0.2.2-py3-none-any.whl (5.8 kB)
Downloading jsonpath_python-1.0.6-py3-none-any.whl (7.6 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: mypy-extensions, jsonpath-python, eval-type-backport, typing-inspect, mistralai
Successfully installed eval-type-backport-0.2.2 jsonpath-python-1.0.6 mistralai-1.5.0 mypy-extensions-1.0.0 typing-inspect-0.9.0

In [ ]:
import os
import requests

from mistralai import Mistral

#api_key = os.environ["LhADdOJJjA1b68o2Vt685bnsCWv07Gv1"]
model = "mistral-large-latest"
#model = "mistral-nemo"

client = Mistral(api_key="LhADdOJJjA1b68o2Vt685bnsCWv07Gv1")

chat_response = client.chat.complete(
    model = model,
    messages = [
        {
            "role": "user",
            "content": "Я профессор в университете, читаю лекции по ИИ. Моё имя Андрей. Поприветствуй меня с учетом информации",
        },
    ]
)

print(chat_response.choices[0].message.content)

Привет, Андрей! Рад познакомиться с тобой. Как профессор, читающий лекции по искусственному интеллекту, ты, наверное, имеешь дело с очень интересными и актуальными темами. Если у тебя есть какие-либо вопросы или тебе нужна помощь с материалом для лекций, не стесняйся обращаться!

In [ ]:
pip install apimoex

Collecting apimoex
  Downloading apimoex-1.4.0-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from apimoex) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31.0->apimoex) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31.0->apimoex) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31.0->apimoex) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31.0->apimoex) (2024.8.30)
Downloading apimoex-1.4.0-py3-none-any.whl (11 kB)
Installing collected packages: apimoex
Successfully installed apimoex-1.4.0

In [ ]:
import requests
import apimoex
import pandas as pd
import plotly
import plotly.graph_objs as go
import plotly.express as px


with requests.Session() as session:
    data = apimoex.get_board_history(session, 'GAZP')
    df = pd.DataFrame(data)
    df.set_index('TRADEDATE', inplace = True)
    print(df.head(), '\n')
    print(df.tail(),'\n')
    df.info

           BOARDID   CLOSE    VOLUME         VALUE
TRADEDATE
2014-06-09    TQBR  144.40  40347300  5.851239e+09
2014-06-10    TQBR  144.75  41460990  5.956067e+09
2014-06-11    TQBR  146.40  39418520  5.725373e+09
2014-06-16    TQBR  145.20  77165360  1.113453e+10
2014-06-17    TQBR  144.77  44370530  6.436430e+09

           BOARDID   CLOSE    VOLUME         VALUE
TRADEDATE
2024-11-21    TQBR  124.10  77481690  9.446569e+09
2024-11-22    TQBR  119.47  72089820  8.709271e+09
2024-11-25    TQBR  117.44  53827410  6.357892e+09
2024-11-26    TQBR  114.50  58959310  6.850075e+09
2024-11-27    TQBR  119.41  93159920  1.079494e+10

In [ ]:
df_n = df[['CLOSE']]
df_n

             CLOSE
TRADEDATE
2014-06-09  144.40
2014-06-10  144.75
2014-06-11  146.40
2014-06-16  145.20
2014-06-17  144.77
...            ...
2024-11-21  124.10
2024-11-22  119.47
2024-11-25  117.44
2024-11-26  114.50
2024-11-27  119.41

[2647 rows x 1 columns]

In [ ]:
fig = px.line(df_n,
              #  title = 'Изменение',
                width=1200, height=600,
                      labels={
                     "value": "Стоимость 1 акции, руб.",
                     "TRADEDATE": "Дата проведения торгов",
                     "species": "Species of Iris"
                 }

              )
fig.update_layout(showlegend=False)
fig.show()

Из графика можно видеть отсутствующие значения, когда торги не проводились (в феврале 2022 г.)

In [ ]:
def buildLaggedFeatures(df_n,lag=5,dropna=True):
 if type(df_n) is pd.DataFrame:
    new_dict={}
    for col_name in df_n:
        new_dict[col_name]=df_n[col_name]
        for l in range(1,lag+1):
            new_dict['%s_lag%d' %(col_name,l)]=df_n[col_name].shift(l)
    res=pd.DataFrame(new_dict,index=df_n.index)
 else:
    return None
 if dropna:
    return res.dropna()
 else:
    return res

In [ ]:
res=buildLaggedFeatures(df_n,lag=10,dropna=True)
res

,CLOSE,CLOSE_lag1,CLOSE_lag2,CLOSE_lag3,CLOSE_lag4,CLOSE_lag5,CLOSE_lag6,CLOSE_lag7,CLOSE_lag8,CLOSE_lag9,CLOSE_lag10
TRADEDATE,,,,,,,,,,,
2014-06-25,149.26,153.25,147.17,145.60,145.20,145.00,144.77,145.20,146.40,144.75,144.40
2014-06-26,147.44,149.26,153.25,147.17,145.60,145.20,145.00,144.77,145.20,146.40,144.75
2014-06-27,149.39,147.44,149.26,153.25,147.17,145.60,145.20,145.00,144.77,145.20,146.40
2014-06-30,148.96,149.39,147.44,149.26,153.25,147.17,145.60,145.20,145.00,144.77,145.20
2014-07-01,148.97,148.96,149.39,147.44,149.26,153.25,147.17,145.60,145.20,145.00,144.77
...,...,...,...,...,...,...,...,...,...,...,...
2024-11-21,124.10,121.89,125.49,129.12,133.37,131.61,132.60,135.16,138.12,135.90,135.52
2024-11-22,119.47,124.10,121.89,125.49,129.12,133.37,131.61,132.60,135.16,138.12,135.90
2024-11-25,117.44,119.47,124.10,121.89,125.49,129.12,133.37,131.61,132.60,135.16,138.12
2024-11-26,114.50,117.44,119.47,124.10,121.89,125.49,129.12,133.37,131.61,132.60,135.16
2024-11-27,119.41,114.50,117.44,119.47,124.10,121.89,125.49,129.12,133.37,131.61,132.60

In [ ]:
train=res.loc[:'2021-06-09']
test=res.loc['2021-06-10':]

In [ ]:
pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

Looking in links: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html
WARNING: The repository located at h2o-release.s3.amazonaws.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host h2o-release.s3.amazonaws.com'.
Collecting h2o
  Downloading h2o-3.46.0.6.tar.gz (265.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.8/265.8 MB 4.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from h2o) (2.32.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2024.8.30)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.46.0.6-py2.py3-none-any.whl size=265859786 sha256=fc89fc90c9783e8e345556807ca1196121c5c31c2187ffc3c3e094154e31546a
  Stored in directory: /root/.cache/pip/wheels/0c/95/eb/b449c73f478dbc4557b80170cf7f2aa6db15862877e9a63536
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.46.0.6

In [ ]:
import h2o
from h2o.automl import H2OAutoML
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.25" 2024-10-15; OpenJDK Runtime Environment (build 11.0.25+9-post-Ubuntu-1ubuntu122.04); OpenJDK 64-Bit Server VM (build 11.0.25+9-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.10/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmprram5b20
  JVM stdout: /tmp/tmprram5b20/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmprram5b20/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         11 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.6
H2O_cluster_version_age:    26 days
H2O_cluster_name:           H2O_from_python_unknownUser_01r6mc
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
hdff = h2o.H2OFrame(train)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
hdfp = h2o.H2OFrame(test)
hdfp.tail()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  CLOSE    CLOSE_lag1    CLOSE_lag2    CLOSE_lag3    CLOSE_lag4    CLOSE_lag5    CLOSE_lag6    CLOSE_lag7    CLOSE_lag8    CLOSE_lag9    CLOSE_lag10
-------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  -------------
 131.61        132.6         135.16        138.12        135.9         135.52        131.92        128.77        128.7         125.6          123.44
 133.37        131.61        132.6         135.16        138.12        135.9         135.52        131.92        128.77        128.7          125.6
 129.12        133.37        131.61        132.6         135.16        138.12        135.9         135.52        131.92        128.77         128.7
 125.49        129.12        133.37        131.61        132.6         135.16        138.12        135.9         135.52        131.92         128.77
 121.89        125.49        129.12        133.37        131.61        132.6         135.16        138.12        135.9         135.52         131.92
 124.1         121.89        125.49        129.12        133.37        131.61        132.6         135.16        138.12        135.9          135.52
 119.47        124.1         121.89        125.49        129.12        133.37        131.61        132.6         135.16        138.12         135.9
 117.44        119.47        124.1         121.89        125.49        129.12        133.37        131.61        132.6         135.16         138.12
 114.5         117.44        119.47        124.1         121.89        125.49        129.12        133.37        131.61        132.6          135.16
 119.41        114.5         117.44        119.47        124.1         121.89        125.49        129.12        133.37        131.61         132.6
[10 rows x 11 columns]

In [ ]:
y = "CLOSE"
x_train = hdff.columns
x_train.remove(y)
aml = H2OAutoML(max_runtime_secs=30, nfolds = 5)
aml.train(x = x_train, y = y, training_frame = hdff)

AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OGeneralizedLinearEstimator : Generalized Linear Modeling
Model Key: GLM_1_AutoML_1_20241128_175345


GLM Model: summary
    family    link      regularization               lambda_search                                                                    number_of_predictors_total    number_of_active_predictors    number_of_iterations    training_frame
--  --------  --------  ---------------------------  -------------------------------------------------------------------------------  ----------------------------  -----------------------------  ----------------------  ----------------------------------------------------------------------------------------
    gaussian  identity  Ridge ( lambda = 0.003797 )  nlambda = 30, lambda.max = 3797.4, lambda.min = 0.003797, lambda.1se = 0.003797  10                            10                             30                      AutoML_1_20241128_175345_training_Key_Frame__upload_ba3c189c4aa9f55a828f18bca6024647.hex

ModelMetricsRegressionGLM: glm
** Reported on train data. **

MSE: 8.402620742686093
RMSE: 2.8987274350456085
MAE: 1.9813635509288072
RMSLE: 0.016587651456654084
Mean Residual Deviance: 8.402620742686093
R^2: 0.9942059743544444
Null degrees of freedom: 1753
Residual degrees of freedom: 1743
Null deviance: 2543688.5654756725
Residual deviance: 14738.196782671408
AIC: 8735.101937224716

ModelMetricsRegressionGLM: glm
** Reported on cross-validation data. **

MSE: 8.763213550581506
RMSE: 2.9602725466722664
MAE: 2.02006817202806
RMSLE: 0.016911321465910335
Mean Residual Deviance: 8.763213550581506
R^2: 0.9939573276475983
Null degrees of freedom: 1753
Residual degrees of freedom: 1743
Null deviance: 2543694.032214146
Residual deviance: 15370.676567719962
AIC: 8808.80331757217

Cross-Validation Metrics Summary:
                        mean       sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  ---------  -----------  ------------  ------------  ------------  ------------  ------------
aic                     1777.82    54.3371      1719.25       1823.63       1804.76       1822.95       1718.5
loglikelihood           0          0            0             0             0             0             0
mae                     2.02002    0.129638     1.84718       2.04815       2.15105       2.12508       1.92862
mean_residual_deviance  8.76244    1.28612      7.32941       9.86767       9.35127       9.84859       7.41528
mse                     8.76244    1.28612      7.32941       9.86767       9.35127       9.84859       7.41528
null_deviance           508739     6024.4       505940        509414        513867        514520        499954
r2                      0.993964   0.000835217  0.994915      0.993201      0.993613      0.993281      0.994809
residual_deviance       3074.14    453.377      2572.62       3463.55       3282.3        3456.86       2595.35
rmse                    2.95358    0.220236     2.70729       3.14128       3.05798       3.13825       2.7231
rmsle                   0.0168687  0.00132848   0.0154844     0.0179715     0.0172539     0.0181905     0.0154434

Scoring History:
     timestamp            duration    iteration    lambda    predictors    deviance_train      deviance_xval       deviance_se         alpha    iterations    training_rmse       training_deviance    training_mae        training_r2
---  -------------------  ----------  -----------  --------  ------------  ------------------  ------------------  ------------------  -------  ------------  ------------------  -------------------  ------------------  ------------------
     2024-11-28 17:54:00  0.000 sec   1            .38E4     11            1442.8745007475109  1444.3292536923257  7.009343147540287   0.0
     2024-11-28 17:54:00  0.003 sec   2            .24E4     11            1438.4189277565533  1440.7578554856573  6.9979453762741635  0.0
     2024-11-28 17:54:00  0.004 sec   3            .15E4     11            1431.2911375276276  1435.0391156954515  6.979682827341212   0.0
     2024-11-28 17:54:00  0.005 sec   4            .91E3     11            1419.9255022785692  1425.8998594413567  6.950465212567908   0.0
     2024-11-28 17:54:00  0.006 sec   5            .56E3     11            1401.9130173473063  1411.3709322797256  6.903940842080358   0.0
     2024-11-28 17:54:00  0.013 sec   6            .35E3     11            1373.637863860112   1388.4491186690855  6.830347816570026   0.0
     2024-11-28 17:54:00  0.014 sec   7            .22E3     11            1329.9144584281219  1352.7217475251891  6.715155434878134   0.0
     2024-11-28 17:54:00  0.015 sec   8            .14E3     11            1263.8806677109296  1298.0935805821146  6.537834442990952   0.0
     2024-11-28 17:54:00  0.017 sec   9            .84E2     11            1167.693580155676   1217.0075290968703  6.271821632790631   0.0
     2024-11-28 17:54:00  0.023 sec   10           .52E2     11            1034.9554017521102  1101.9399480098368  5.887995733184392   0.0
---  ---                  ---         ---          ---       ---           ---                 ---                 ---                 ---      ---           ---                 ---                  ---                 ---
     2024-11-28 17:54:00  0.106 sec   22           .17E0     11            25.155197559636058  26.808456023778678  1.0157273058487608  0.0
     2024-11-28 17:54:00  0.107 sec   23           .11E0     11            21.671605225932808  23.314193395105328  0.9501454571091856  0.0
     2024-11-28 17:54:00  0.112 sec   24           .66E-1    11            18.360300811353813  19.895900621185     0.882367889321225   0.0
     2024-11-28 17:54:00  0.117 sec   25           .41E-1    11            15.475051514226667  16.78981166867375   0.8148144184450794  0.0
     2024-11-28 17:54:00  0.118 sec   26           .26E-1    11            13.156195957379303  14.207425601113934  0.7524235351162155  0.0
     2024-11-28 17:54:00  0.125 sec   27           .16E-1    11            11.375062744435828  12.192840164601082  0.6981613904306286  0.0
     2024-11-28 17:54:00  0.132 sec   28           .98E-2    11            10.046532903159697  10.667880421441172  0.6524830001779992  0.0
     2024-11-28 17:54:00  0.134 sec   29           .61E-2    11            9.08620053184396    9.55715770853693    0.6117245736077227  0.0
     2024-11-28 17:54:00  0.142 sec   30           .38E-2    11            8.402620208966827   8.762444927715233   0.5751692466381316  0.0
     2024-11-28 17:54:00  0.152 sec   31           .0E0      11            7.308559115869901   0.0                 0.0                 0.0      31            2.8987274350456085  8.402620742686093    1.9813635509288072  0.9942059743544444
[31 rows x 15 columns]


Variable Importances:
variable     relative_importance    scaled_importance    percentage
-----------  ---------------------  -------------------  ------------
CLOSE_lag1   27.2395                1                    0.670718
CLOSE_lag2   8.04177                0.295224             0.198012
CLOSE_lag3   2.44854                0.089889             0.0602902
CLOSE_lag4   1.16708                0.0428449            0.0287369
CLOSE_lag6   0.931436               0.0341943            0.0229347
CLOSE_lag10  0.36662                0.0134591            0.00902727
CLOSE_lag8   0.242688               0.00890938           0.00597568
CLOSE_lag9   0.121691               0.00446743           0.00299639
CLOSE_lag5   0.0484556              0.00177887           0.00119312
CLOSE_lag7   0.00470892             0.000172871          0.000115948

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
pred = aml.predict(hdfp)
pred.tail()

glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

  predict
---------
  133.703
  132.249
  133.041
  130.141
  126.814
  123.327
  123.818
  120.633
  118.323
  115.614
[10 rows x 1 column]

In [ ]:
aml.leaderboard

model_id                                                     rmse         mse       mae      rmsle    mean_residual_deviance
-------------------------------------------------------  --------  ----------  --------  ---------  ------------------------
GLM_1_AutoML_1_20241128_175345                            2.96027     8.76321   2.02007  0.0169113                   8.76321
StackedEnsemble_AllModels_1_AutoML_1_20241128_175345      2.9628      8.77818   2.02657  0.0169197                   8.77818
StackedEnsemble_BestOfFamily_2_AutoML_1_20241128_175345   2.96535     8.7933    2.02746  0.0169396                   8.7933
StackedEnsemble_BestOfFamily_1_AutoML_1_20241128_175345   2.96778     8.80771   2.02314  0.0169397                   8.80771
DRF_1_AutoML_1_20241128_175345                            4.41994    19.5359    3.09946  0.0253345                  19.5359
GBM_1_AutoML_1_20241128_175345                            6.66394    44.4081    4.4207   0.0352167                  44.4081
GBM_2_AutoML_1_20241128_175345                           28.1367    791.672    22.3935   0.155013                  791.672
GBM_3_AutoML_1_20241128_175345                           29.7988    887.968    23.5751   0.164621                  887.968
GBM_4_AutoML_1_20241128_175345                           30.4921    929.765    24.5504   0.168273                  929.765
XGBoost_1_AutoML_1_20241128_175345                       74.3381   5526.15     47.0538   0.749021                 5526.15
[11 rows x 6 columns]

In [ ]:
#aml.explain(hdfp)

In [ ]:
predict = pred.as_data_frame() # перегоняем обратно в датафрейм

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning:

Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

In [ ]:
r1 = pd.DataFrame(columns=['Дата', 'Значение', 'Тип'])
r1['Дата']=train.index.values
r1['Значение']=train[['CLOSE']].values
r1['Тип'] = 'Обучающая выборка'

In [ ]:
r2 = pd.DataFrame(columns=['Дата', 'Значение', 'Тип'])
r2['Дата']=test.index.values
r2['Значение']=test[['CLOSE']].values
r2['Тип'] = 'Тестовая выборка'

In [ ]:
r3 = pd.DataFrame(columns=['Дата', 'Значение', 'Тип'])
r3['Дата']=test.index.values
r3['Значение']=predict.values
r3['Тип'] = 'Предсказание модели'

In [ ]:
r= pd.concat([r1,r2,r3])

In [ ]:
fig = px.line(r, x="Дата", y="Значение", color='Тип',
                width=1200, height=600,
                         labels={
                     "Значение": "Стоимость 1 акции, руб.",
                     "Дата": "Дата проведения торгов",

                 }
              )
fig.update_layout(showlegend=True)
fig.show()

In [ ]:
col = res.columns [1:]
day = res.iloc[:,:-1].tail(1).values
day = pd.DataFrame(day, columns=col)
day

,CLOSE_lag1,CLOSE_lag2,CLOSE_lag3,CLOSE_lag4,CLOSE_lag5,CLOSE_lag6,CLOSE_lag7,CLOSE_lag8,CLOSE_lag9,CLOSE_lag10
0,119.41,114.5,117.44,119.47,124.1,121.89,125.49,129.12,133.37,131.61

In [ ]:
day = h2o.H2OFrame(day)
day

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  CLOSE_lag1    CLOSE_lag2    CLOSE_lag3    CLOSE_lag4    CLOSE_lag5    CLOSE_lag6    CLOSE_lag7    CLOSE_lag8    CLOSE_lag9    CLOSE_lag10
------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  -------------
      119.41         114.5        117.44        119.47         124.1        121.89        125.49        129.12        133.37         131.61
[1 row x 10 columns]

In [ ]:
# прозноз на 1 день (на завтра)
pred1 = aml.predict(day)
pred1.tail()

glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

  predict
---------
  118.333
[1 row x 1 column]